### ISSUE TITLE
Porting to Python 3

### ISSUE THREAD

**Issue by maciejlach** [exxeleron/qPython#21]

**Comment by 691175002** [comment]
Is there a timeline for implementing this?

**Comment by maciejlach** [comment]
Timeline for the final version is not yet defined.

You can check out the development branch for qpython 1.1 at: https://github.com/exxeleron/qPython/tree/qpython-1.1-dev. 

Note that the documentation has not been updated yet, thus please refer to unit tests: [serialization](https://github.com/exxeleron/qPython/blob/qpython-1.1-dev/tests/qwriter_test.py), [deserialization](https://github.com/exxeleron/qPython/blob/qpython-1.1-dev/tests/qreader_test.py), [pandas](https://github.com/exxeleron/qPython/blob/qpython-1.1-dev/tests/pandas_test.py) for usage examples compatible with both Python 2.7 and 3.4.
