### ISSUE TITLE
Dump QTable

### ISSUE THREAD

**Issue by shashicstl** [exxeleron/qPython#27]
Hello,

I am trying to use qpython for the first time. One of my use cases is to run a query and dump data to csv file. Is there an easy way to do so? I can write individual rows, but how do I get column names.

Many thanks.

**Comment by maciejlach** [comment]
The `QTable` class extends `numpy.recarray`, so you can use [`numpy.savetxt`](http://docs.scipy.org/doc/numpy/reference/generated/numpy.savetxt.html) to save it as a CSV:

```python
    np = q('flip `name`iq!(`Dent`Beeblebrox`Prefect;98 42 126)')
    numpy.savetxt('np.csv', np, delimiter = ',', header = ','.join(np.dtype.names), fmt = '%s')
```

Or if you prefer to represent tables as pandas `DataFrame`s, use [`pandas.DataFrame.to_csv`](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.to_csv.html):

```python
    df = q('flip `name`iq!(`Dent`Beeblebrox`Prefect;98 42 126)', pandas = True)
    df.to_csv('df.csv', sep = ',')
```

**Comment by shashicstl** [comment]
Awesome thank you. New to qpython, numpy and pandas.

I was able to test dumping to csv using pandas df. Works, however I see that timestammps have '0 days' in them, eg: 0 days 05:01:12.965000000

I'd like to get rid of '0 days' part and print up to milliseconds.

Can you point me to doc that let's me how to format etc?

**Comment by maciejlach** [comment]
You can refer to this stackoverflow post:
http://stackoverflow.com/questions/13999850/how-to-specify-date-format-when-using-pandas-to-csv

**Comment by shashicstl** [comment]
Thank you.

Appreciate help.
